// Generated by CoffeeScript 1.7.1
(function() {
  var Dismiss;

  Dismiss = (function() {
    function Dismiss() {
      this.iconCode = '&#10006;';
    }

    Dismiss.prototype.apply = function(paintable) {
      return paintable.dismiss();
    };

    Dismiss.prototype.remove = function() {
      return this.palette.remove();
    };

    return Dismiss;

  })();

  window.PaintMe.Actions.Dismiss = Dismiss;

}).call(this);
