// Generated by CoffeeScript 1.7.1
(function() {
  var CanvasTextArea, PrintText, SelectTextZone,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  CanvasTextArea = (function() {
    function CanvasTextArea(canvas, coords, opts) {
      this.canvas = canvas;
      this.context = canvas.context;
      this.text = [];
      this.opts = opts;
      this.startX = opts[0];
      this.startY = opts[1];
      this.lastX = opts[2];
      this.lastY = opts[3];
      this.width = this.lastX - this.startX;
      this.height = this.lastY - this.startY;
    }

    CanvasTextArea.prototype.printChar = function(char) {
      var span, width;
      this.text += char;
      span = $("<span style='display: none'>" + this.text + "</span>");
      $('body').append(span);
      width = span.width();
      span.remove();
      console.log("Text: " + this.text);
      console.log("Text width: " + width);
      this.context.fillStyle = 'blue';
      this.context.font = 'bold 16px Arial';
      return this.context.fillText("Zib\nri", this.startX, this.startY);
    };

    return CanvasTextArea;

  })();

  SelectTextZone = (function() {
    function SelectTextZone(paintObj) {
      this.onPick = __bind(this.onPick, this);
      console.log('SelectTextZone constr');
      this.iconSrc = 'icons/pen.svg';
      this.iconBase64 = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAwklEQVQ4T52TYQ3CMBBG3xSAE5CAg80BQwGghOBgUwBTMHCABCSAA/KRNjmaFa7cvyZ9r+1314qymgMnYAWcgU1VxtMBa8MMXoFO3gJH4AIsosQjEDwCS3jfYG8k118CCz+BmZEog903gYV7bQbuQaKnaE1OkMJtOFkB6ibqwi0ncMNTgiI4FRTDVvAXbAUKRMMxAE0usKmpVReUqAZF9QhDIslH2rmRl0D9PCQbXHB8giaqNgI3HAX6HPHqykJrd70A06I+wCwcPxUAAAAASUVORK5CYII=';
      this.painting = false;
      $('body').on('keydown', (function(_this) {
        return function(e) {};
      })(this));
    }

    SelectTextZone.prototype.onmousedown = function(paintable, event) {
      this.painting = true;
      this.startX = event.layerX || 0;
      this.startY = event.layerY || 0;
      this.initialImage = new Image;
      this.initialImage.src = paintable.context.canvas.toDataURL();
      return $('body').on('keydown', (function(_this) {
        return function(e) {
          if (_this.textArea) {
            return _this.textArea.printChar(String.fromCharCode(e.keyCode));
          }
        };
      })(this));
    };

    SelectTextZone.prototype.onmousemove = function(paintable, event) {
      var context;
      context = paintable.context;
      if (this.painting === true) {
        context.drawImage(this.initialImage, 0, 0);
        context.beginPath();
        context.strokeStyle = paintable.toolbar.color;
        context.rect(this.startX, this.startY, event.layerX - this.startX, event.layerY - this.startY);
        context.stroke();
        return context.closePath();
      }
    };

    SelectTextZone.prototype.onmouseup = function(paintable, event) {
      var context;
      context = paintable.context;
      this.painting = false;
      return this.textArea = new CanvasTextArea(paintable, [this.startX, this.startY, event.layerX - this.startX, event.layerY - this.startY], {});
    };

    SelectTextZone.prototype.onPick = function(paintable) {
      return 1;
    };

    return SelectTextZone;

  })();

  PrintText = (function() {
    function PrintText() {
      this.iconCode = '&#xEA01;';
      this.iconSrc = 'icons/1.svg';
    }

    PrintText.prototype.apply = function(paintable) {
      this.paintable = paintable;
      return this.addTextControls();
    };

    PrintText.prototype.addTextControls = function(toolbarElement) {
      var name, textControl;
      name = 'SelectTextZone';
      textControl = $("<div class='controls text'></div>").appendTo(this.paintable.toolbar.element);
      textControl.append($('<div class="tool" data-name="' + name + '">' + '<img class="svg" src="123">' + '</div>'));
      return this.paintable.toolbar.includeTool(name, SelectTextZone);
    };

    return PrintText;

  })();

}).call(this);
