// Generated by CoffeeScript 1.7.1
(function() {
  var Redo;

  Redo = (function() {
    function Redo() {
      this.iconCode = '&#xEA07;';
      this.iconSrc = 'icons/redo.svg';
    }

    Redo.prototype.apply = function(paintable) {
      return paintable.redo();
    };

    return Redo;

  })();

  window.PaintMe.Actions.Redo = Redo;

}).call(this);
