// Generated by CoffeeScript 1.7.1
(function() {
  var Undo;

  Undo = (function() {
    function Undo() {
      this.iconCode = '&#xEA0A;';
      this.iconSrc = 'icons/undo.svg';
    }

    Undo.prototype.apply = function(paintable) {
      return paintable.undo();
    };

    return Undo;

  })();

  window.PaintMe.Actions.Undo = Undo;

}).call(this);
