// Generated by CoffeeScript 1.7.1
(function() {
  var CircleShape;

  CircleShape = (function() {
    function CircleShape() {
      this.iconCode = '&#xEA01;';
      this.iconSrc = 'icons/circle_shape.svg';
      this.iconBase64 = '';
      this.painting = false;
    }

    CircleShape.prototype.onmousedown = function(paintable, event) {
      var context;
      context = paintable.context;
      this.painting = true;
      this.startX = event.layerX || 0;
      this.startY = event.layerY || 0;
      this.startY -= window.pageYOffset;
      this.previousState = context.canvas.toDataURL();
      this.initialImage = new Image;
      return this.initialImage.src = this.previousState;
    };

    CircleShape.prototype.onmousemove = function(paintable, event) {
      var context;
      context = paintable.context;
      if (this.painting === true) {
        context.drawImage(this.initialImage, 0, 0);
        context.beginPath();
        context.arc(this.startX, this.startY, Math.abs(event.layerX - this.startX), 0, 2 * Math.PI, false);
        context.lineWidth = 5;
        context.strokeStyle = paintable.toolbar.color;
        return context.stroke();
      }
    };

    CircleShape.prototype.onmouseup = function(paintable, event) {
      var context;
      context = paintable.context;
      return this.painting = false;
    };

    CircleShape.prototype.onPick = function(paintable) {};

    return CircleShape;

  })();

  window.PaintMe.Instruments.CircleShape = CircleShape;

}).call(this);
