// Generated by CoffeeScript 1.7.1
(function() {
  var Pen,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Pen = (function() {
    function Pen() {
      this.onPick = __bind(this.onPick, this);
      this.iconCode = '&#xEA05;';
      this.iconSrc = 'icons/pen.svg';
      this.iconBase64 = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAwklEQVQ4T52TYQ3CMBBG3xSAE5CAg80BQwGghOBgUwBTMHCABCSAA/KRNjmaFa7cvyZ9r+1314qymgMnYAWcgU1VxtMBa8MMXoFO3gJH4AIsosQjEDwCS3jfYG8k118CCz+BmZEog903gYV7bQbuQaKnaE1OkMJtOFkB6ibqwi0ncMNTgiI4FRTDVvAXbAUKRMMxAE0usKmpVReUqAZF9QhDIslH2rmRl0D9PCQbXHB8giaqNgI3HAX6HPHqykJrd70A06I+wCwcPxUAAAAASUVORK5CYII=';
      this.painting = false;
    }

    Pen.prototype.onmousedown = function(paintable, event) {
      var context;
      context = paintable.context;
      this.painting = true;
      this.lastX = event.layerX;
      this.lastY = event.layerY - window.pageYOffset;
    };

    Pen.prototype.onmousemove = function(paintable, event) {
      var context;
      console.log(event);
      context = paintable.context;
      if (this.painting === true) {
        context.beginPath();
        context.strokeStyle = paintable.toolbar.color;
        context.lineWidth = 3;
        context.lineJoin = 'round';
        context.moveTo(this.lastX, this.lastY);
        context.lineTo(event.layerX, event.layerY - window.pageYOffset);
        context.closePath();
        context.stroke();
      }
      this.lastX = event.layerX;
      this.lastY = event.layerY - window.pageYOffset;
    };

    Pen.prototype.onmouseup = function(paintable, event) {
      var context;
      context = paintable.context;
      this.painting = false;
    };

    Pen.prototype.onPick = function(paintable) {};

    return Pen;

  })();

  window.PaintMe.Instruments.Pen = Pen;

}).call(this);
