// Generated by CoffeeScript 1.7.1
(function() {
  var RectangleShape;

  RectangleShape = (function() {
    function RectangleShape() {
      this.iconCode = '&#xEA06;';
      this.iconSrc = 'icons/rectShape.svg';
      this.iconBase64 = '';
      this.painting = false;
    }

    RectangleShape.prototype.onmousedown = function(paintable, event) {
      var context;
      context = paintable.context;
      this.painting = true;
      this.startX = event.layerX || 0;
      this.startY = event.layerY || 0;
      this.startY -= window.pageYOffset;
      this.previousState = context.canvas.toDataURL();
      this.initialImage = new Image;
      return this.initialImage.src = this.previousState;
    };

    RectangleShape.prototype.onmousemove = function(paintable, event) {
      var context;
      context = paintable.context;
      if (this.painting === true) {
        context.drawImage(this.initialImage, 0, 0);
        context.beginPath();
        context.strokeStyle = paintable.toolbar.color;
        context.rect(this.startX, this.startY, event.layerX - this.startX, event.layerY - this.startY - window.pageYOffset);
        context.stroke();
        return context.closePath();
      }
    };

    RectangleShape.prototype.onmouseup = function(paintable, event) {
      var context;
      context = paintable.context;
      return this.painting = false;
    };

    RectangleShape.prototype.onPick = function(paintable) {};

    return RectangleShape;

  })();

  window.PaintMe.Instruments.RectangleShape = RectangleShape;

}).call(this);
